[package]
name = "biblearchive-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
biblearchive = { path = "../biblearchive"}
clap = { version = "4.5.53", features = ["derive"] }
humansize = "2.1.3"
